# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('points_to_award', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rating', models.FloatField()),
                ('uploaded_image', models.ImageField(upload_to=b'')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordHuntApp.Image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('total_points', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('currently_participates', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('text', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordHuntApp.Image')),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordHuntApp.User'),
        ),
        migrations.AddField(
            model_name='image',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordHuntApp.User'),
        ),
        migrations.AddField(
            model_name='competition',
            name='word',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WordHuntApp.Word'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordHuntApp.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WordHuntApp.User'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('username', 'image')]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('username', 'image', 'creation_date')]),
        ),
    ]
