# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WordHuntApp', '0003_auto_20180301_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='related_word',
            field=models.ForeignKey(default='bla', on_delete=django.db.models.deletion.CASCADE, to='WordHuntApp.Word'),
            preserve_default=False,
        ),
    ]
