# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordHuntApp', '0005_auto_20180309_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([]),
        ),
    ]
