# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordHuntApp', '0006_auto_20180309_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
