# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-17 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordHuntApp', '0007_auto_20180316_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
