# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-17 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordHuntApp', '0008_competition_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
