# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordHuntApp', '0009_auto_20180317_1851'),
        ('WordHuntApp', '0007_auto_20180320_0008'),
    ]

    operations = [
    ]
