# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordHuntApp', '0012_auto_20180321_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='competition_rank',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='competitions_won',
        ),
    ]
