# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordHuntApp', '0013_auto_20180321_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='competition_rank',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='competitions_won',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
