# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordHuntApp', '0016_auto_20180322_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
