# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WordHuntApp', '0017_auto_20180322_2132'),
        ('WordHuntApp', '0017_auto_20180325_2055'),
    ]

    operations = [
    ]
